/*
* code generated by whisperer
* line number 10 to 11
 */
package com.persistent.jobs.utility;

//create Helper class for export excel file
import com.persistent.jobs.entity.Jobs;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.util.List;

/**
 * Created by Pravin on 12/1/2016.
 */
public class Helper {

    public static String[] Headers ={
            "job_id",
            "company",
            "job_location",
            "job_skills",
            "job_title",
            "job_description",
            "posted_date",
    };
    public static String SHEET_NAME = "Jobs_Data";

    //create a method dataToExcel()
    public static ByteArrayInputStream dataToExcel(List<Jobs> listJobs) throws IOException {
        //create workbook
        Workbook workbook = new XSSFWorkbook();
        ByteArrayOutputStream out = new ByteArrayOutputStream();
        //create sheet
        org.apache.poi.ss.usermodel.Sheet sheet = workbook.createSheet(SHEET_NAME);
        //create row
        org.apache.poi.ss.usermodel.Row headerRow = sheet.createRow(0);
        try {
            for (int i = 0; i < Headers.length; i++) {
                org.apache.poi.ss.usermodel.Cell cell = headerRow.createCell(i);
                cell.setCellValue(Headers[i]);
            }
            //value rows
            int rowNum = 1;
            for (Jobs jobs : listJobs) {
                //create Row
                org.apache.poi.ss.usermodel.Row row = sheet.createRow(rowNum++);
                row.createCell(0).setCellValue(jobs.getJobId());
                row.createCell(1).setCellValue(jobs.getCompany());
                row.createCell(2).setCellValue(jobs.getJobLocation());
                row.createCell(3).setCellValue(jobs.getJobSkills());
                row.createCell(4).setCellValue(jobs.getJobTitle());
                row.createCell(5).setCellValue(jobs.getJobsDescription());
                row.createCell(6).setCellValue(jobs.getPostedDate());
            }
            workbook.write(out);
            return new ByteArrayInputStream(out.toByteArray());
        } catch (IOException e) {
            e.printStackTrace();
            System.out.println("fail to export data in excel sheet");
            return null;
        } finally{
            workbook.close();
            out.close();
        }
    }
}